# Generated by Django 5.0 on 2023-12-30 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_code_created_at_code_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='code',
            name='identifier',
        ),
        migrations.AddField(
            model_name='code',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
            preserve_default=False,
        ),
    ]
